### ISSUE TITLE
Import relevant commit history from experimental repository

### ISSUE THREAD

**Issue by per1234** [arduino/report-size-deltas#2]
The initial development work on the action was done in [a repository](https://github.com/arduino/actions) used to host actions while they are in their unstable, experimental stage of development. The valuable commit history should be imported into the dedicated repository for the action.

---
Since it's not possible to add this commit history to the repository via a pull request, I have pushed it to a development branch.
https://github.com/arduino/report-size-deltas/tree/per1234/development-initial-import

This development branch itself should be reviewed. Once it is approved, I'll push it to the primary `main` branch.

---
All commits relevant to this action were filtered from the full history of that repository using the excellent [`newren/git-filter-repo`](https://github.com/newren/git-filter-repo):
```
git clone https://github.com/newren/git-filter-repo
cd git-filter-repo
# checkout latest tag
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
export PATH="$PATH:$PWD"
cd ..
git clone https://github.com/arduino/actions
cd actions
git filter-repo --path LICENSE \
                --path .github/workflows/libraries_report-size-deltas.yml \
                --path .github/workflows/spell-check.yml \
                --path etc/codespell-ignore-words-list.txt \
                --path libraries/report-size-deltas --path-rename libraries/report-size-deltas/: \
                --message-callback 'return message.split(b"libraries/report-size-deltas:", maxsplit=1)[1].strip()[:1].upper() + message.split(b"libraries/report-size-deltas:", maxsplit=1)[1].strip()[1:] if message.startswith(b"libraries/report-size-deltas:") else message.strip()'
# Create branch to use for review before pushing to main
git checkout -b per1234/development-initial-import
# git-filter-repo removes the original "origin" remote
git remote add origin https://github.com/arduino/report-size-deltas
git push --set-upstream origin per1234/development-initial-import
```

---
I have also submitted a PR to update the CI workflows. You can see from the CI runs on that PR that all checks are still passing after the import:
https://github.com/arduino/report-size-deltas/pull/1/checks

Note: the initial run of the Spell Check workflow on the `per1234/development-initial-import` branch is expected to fail because that run was from the unchanged imported workflow that is still configured for the experimental repository.

---
Note: this is only an initial import. The outdated parts of the documentation will be updated in a PR soon to come after the import is approved.

**Comment by aentinger** [comment]
All good :+1: :rocket:
